version: "3.7"

services:
    db:
        build: .
        container_name: api-db
        image: postgres:latest
        restart: always
        tty: true
        ports:
          - "5432:5432"
        volumes:
          - authsystemdb:/var/lib/postgresql

        environment:
          - POSTGRES_USER=docker
          - POSTGRES_PASSWORD=docker

volumes:
  authsystemdb: